# Generated by Django 3.2.6 on 2021-10-06 11:02

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import exchange.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(default=exchange.models.generate_pk, editable=False, max_length=20)),
                ('buying_currency', models.CharField(blank=True, choices=[('AED', 'AED'), ('ARS', 'ARS'), ('AUD', 'AUD'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('BSD', 'BSD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('EGP', 'EGP'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('GBP', 'GBP'), ('GTQ', 'GTQ'), ('HKD', 'HKD'), ('HRK', 'HRK'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('ISK', 'ISK'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('KZT', 'KZT'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PAB', 'PAB'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('PYG', 'PYG'), ('RON', 'RON'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SAR', 'SAR'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('TWD', 'TWD'), ('UAH', 'UAH'), ('USD', 'USD'), ('UYU', 'UYU'), ('VND', 'VND'), ('ZAR', 'ZAR')], max_length=5, null=True)),
                ('selling_currency', models.CharField(blank=True, choices=[('AED', 'AED'), ('ARS', 'ARS'), ('AUD', 'AUD'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('BSD', 'BSD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('EGP', 'EGP'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('GBP', 'GBP'), ('GTQ', 'GTQ'), ('HKD', 'HKD'), ('HRK', 'HRK'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('ISK', 'ISK'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('KZT', 'KZT'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PAB', 'PAB'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('PYG', 'PYG'), ('RON', 'RON'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SAR', 'SAR'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('TWD', 'TWD'), ('UAH', 'UAH'), ('USD', 'USD'), ('UYU', 'UYU'), ('VND', 'VND'), ('ZAR', 'ZAR')], max_length=5, null=True)),
                ('buying_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selling_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_id', models.CharField(max_length=80, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('assign_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.agent')),
                ('customer_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_info', to='administration.customer')),
                ('exchange_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_exchange_rate', to='administration.currencyrate')),
            ],
        ),
    ]
