# Generated by Django 3.2.6 on 2021-10-09 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transfer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateField(auto_now_add=True)),
                ('send_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('cash', 'Cash Transfer'), ('cheque', 'Cheque Transfer'), ('debt', 'Debt')], max_length=30, null=True)),
                ('receive_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('cash', 'Cash Transfer'), ('cheque', 'Cheque Transfer')], max_length=30, null=True)),
                ('sending_currency', models.CharField(choices=[('AED', 'AED'), ('ARS', 'ARS'), ('AUD', 'AUD'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('BSD', 'BSD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('EGP', 'EGP'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('GBP', 'GBP'), ('GTQ', 'GTQ'), ('HKD', 'HKD'), ('HRK', 'HRK'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('ISK', 'ISK'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('KZT', 'KZT'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PAB', 'PAB'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('PYG', 'PYG'), ('RON', 'RON'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SAR', 'SAR'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('TWD', 'TWD'), ('UAH', 'UAH'), ('USD', 'USD'), ('UYU', 'UYU'), ('VND', 'VND'), ('ZAR', 'ZAR')], max_length=5, null=True)),
                ('receiving_currency', models.CharField(choices=[('AED', 'AED'), ('ARS', 'ARS'), ('AUD', 'AUD'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('BSD', 'BSD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('EGP', 'EGP'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('GBP', 'GBP'), ('GTQ', 'GTQ'), ('HKD', 'HKD'), ('HRK', 'HRK'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('ISK', 'ISK'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('KZT', 'KZT'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PAB', 'PAB'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('PYG', 'PYG'), ('RON', 'RON'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SAR', 'SAR'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('TWD', 'TWD'), ('UAH', 'UAH'), ('USD', 'USD'), ('UYU', 'UYU'), ('VND', 'VND'), ('ZAR', 'ZAR')], max_length=5, null=True)),
                ('transfer_rate', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('transaction_id', models.CharField(default=transfer.models.generate_pk, editable=False, max_length=20)),
                ('sending_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('receiving_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('outstanding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('payment_status', models.CharField(choices=[('sent', 'Sent'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='Sent', max_length=30, null=True)),
                ('notification_type', models.CharField(choices=[('sms', 'Sms'), ('email', 'Email'), ('both', 'Both')], max_length=30, null=True)),
                ('notes', models.CharField(blank=True, max_length=150)),
                ('agent_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.bankuser')),
                ('exchange_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rate', to='administration.currencyrate')),
                ('reason_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.reasontype')),
                ('receiver_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_agent', to=settings.AUTH_USER_MODEL)),
                ('receiver_cu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_cu', to=settings.AUTH_USER_MODEL)),
                ('sender_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_agent', to=settings.AUTH_USER_MODEL)),
                ('sender_cu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_cu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebtTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_id', models.CharField(blank=True, max_length=20, null=True)),
                ('sending_currency', models.CharField(blank=True, choices=[('AED', 'AED'), ('ARS', 'ARS'), ('AUD', 'AUD'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('BSD', 'BSD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('EGP', 'EGP'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('GBP', 'GBP'), ('GTQ', 'GTQ'), ('HKD', 'HKD'), ('HRK', 'HRK'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('ISK', 'ISK'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('KZT', 'KZT'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PAB', 'PAB'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('PYG', 'PYG'), ('RON', 'RON'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SAR', 'SAR'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('TWD', 'TWD'), ('UAH', 'UAH'), ('USD', 'USD'), ('UYU', 'UYU'), ('VND', 'VND'), ('ZAR', 'ZAR')], max_length=5, null=True)),
                ('receiving_currency', models.CharField(blank=True, choices=[('AED', 'AED'), ('ARS', 'ARS'), ('AUD', 'AUD'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('BSD', 'BSD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('EGP', 'EGP'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('GBP', 'GBP'), ('GTQ', 'GTQ'), ('HKD', 'HKD'), ('HRK', 'HRK'), ('HUF', 'HUF'), ('IDR', 'IDR'), ('ILS', 'ILS'), ('INR', 'INR'), ('ISK', 'ISK'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('KZT', 'KZT'), ('MXN', 'MXN'), ('MYR', 'MYR'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PAB', 'PAB'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PKR', 'PKR'), ('PLN', 'PLN'), ('PYG', 'PYG'), ('RON', 'RON'), ('RUB', 'RUB'), ('SAR', 'SAR'), ('SEK', 'SEK'), ('SAR', 'SAR'), ('SGD', 'SGD'), ('THB', 'THB'), ('TRY', 'TRY'), ('TWD', 'TWD'), ('UAH', 'UAH'), ('USD', 'USD'), ('UYU', 'UYU'), ('VND', 'VND'), ('ZAR', 'ZAR')], max_length=5, null=True)),
                ('sending_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('receiving_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('outstanding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('debt', models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('cash', 'Cash Transfer'), ('cheque', 'Cheque Transfer'), ('debt', 'Debt')], max_length=30, null=True)),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_ratedb', to='administration.currencyrate')),
                ('receiver_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_customer', to=settings.AUTH_USER_MODEL)),
                ('sender_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_agentdb', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
