# Generated by Django 3.2.6 on 2021-10-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debttransfer',
            old_name='receiving_currency',
            new_name='from_currency',
        ),
        migrations.RenameField(
            model_name='debttransfer',
            old_name='sending_currency',
            new_name='to_currency',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='receiving_currency',
            new_name='from_currency',
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='sending_currency',
            new_name='to_currency',
        ),
        migrations.RemoveField(
            model_name='debttransfer',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='debttransfer',
            name='total_commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_commission1', to='administration.currencyrate'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='total_commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_commission2', to='administration.currencyrate'),
        ),
    ]
